config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  if AuthenticationType.cas?
    devise_scope :user do
      get '/users/sign_out' => 'devise/cas_sessions#destroy'
    end
  end

  root to: 'dashboard#show'
  resources :home_offices, only: [:create, :destroy]
  resources :teams, only: [:index, :new, :create]
  resources :user, only: :update
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home_office.rb
# frozen_string_literal: true
class HomeOffice < ApplicationRecord
  validates :date, :user, :team, presence: true
  belongs_to :user
  belongs_to :team

  def self.current_period_for(team)
    where(date: (40.days.ago..40.days.from_now), team: team)
  end
end

app/models/team.rb
# frozen_string_literal: true
class Team < ApplicationRecord
  validates :name, uniqueness: true
  has_many :users
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include AuthenticationType

  has_many :home_offices
  belongs_to :team, optional: true

  def cas_extra_attributes=(extra_attributes)
    self.name = extra_attributes['cn']
    self.user_type = extra_attributes['type']
    self.email = extra_attributes['email']
    if extra_attributes['authorities'].is_a?(Array)
      self.user_privilegies = extra_attributes['authorities'].join(',')
    else
      self.user_privilegies = extra_attributes['authorities']
    end
  end

  def gravatar_url
    require 'digest'

    md5 = Digest::MD5.new
    md5.update email
    "https://www.gravatar.com/avatar/#{md5.hexdigest}?s=40"
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true
class DashboardController < ApplicationController
  before_action :request_team

  def show
    @home_office = HomeOffice.new
    @home_offices = HomeOffice.current_period_for(current_user.team)
  end

  private

  def request_team
    return if current_user.team.present?
    flash[:alert] = I18n.t('.teams.select_team')
    redirect_to teams_path
  end
end

app/controllers/home_offices_controller.rb
# frozen_string_literal: true
class HomeOfficesController < ApplicationController
  def create
    @home_office = current_user.home_offices.new(home_office_params)
    @home_office.team = current_user.team
    if @home_office.save
      flash[:success] = 'Home office marcado com sucesso!'
    else
      flash[:error] = 'Erro ao marcar Home office!'
    end
    redirect_to root_path
  end

  def destroy
    @home_office = HomeOffice.find(params[:id])

    if @home_office.user == current_user
      @home_office.destroy
      flash[:success] = 'Home office desmarcado com sucesso!'
    else
      flash[:error] = 'Você não pode desmarcar esse Home office'
    end

    redirect_to root_path
  end

  private

  def home_office_params
    params.require(:home_office).permit(:date)
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true
class TeamsController < ApplicationController
  layout 'pre_panel'

  def index
    @teams = Team.all
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      flash.now[:success] = t('.success', team: @team.name)
    else
      flash.now[:error] = t('.error', team: @team.name)
    end
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end
end

app/controllers/user_controller.rb
# frozen_string_literal: true
class UserController < ApplicationController
  def update
    @user = User.find(params[:id])
    flash[:success] = I18n.t('.users.user_updated') if @user.update(user_params)
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:team_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true
module ApplicationHelper
  def locastyle_class_for_alert(flash_type)
    message = { error: 'danger', alert: 'warning', notice: 'info' }
    'ls-alert-' + (message[flash_type.to_sym] || flash_type.to_s)
  end
end

app/helpers/home_offices_helper.rb
# frozen_string_literal: true
module HomeOfficesHelper
  def current_user_home_office?(home_office)
    home_office.user == current_user
  end

  def home_office_css(home_office)
    if current_user_home_office?(home_office)
      'calendar-user calendar-user-ho'
    else
      'calendar-user'
    end
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true
module UsersHelper
  def home_office_at_date?(date)
    current_user.home_offices.where(date: date).present?
  end
end

app/views/dashboard/show.html.erb
<%= render 'layouts/topbar' %>
<%= render 'layouts/sidebar' %>

<main class="ls-main">
  <div class="container-fluid">
    <h1 class="ls-title-intro ls-ico-dashboard"><%= t('dashboard') %></h1>

    <%= render partial: "shared/flash_messages" %>

    <div class="ls-box ls-board-box">
      <header class="ls-info-header">
        <h2 class="ls-title-3">Informações Gerais</h2>
      </header>

      <div id="sending-stats" class="row">
        <div class="col-sm-6 col-md-4">
          <div class="ls-box">
            <div class="ls-box-head">
              <h6 class="ls-title-4">Quantidade de HOs Feitos</h6>
            </div>

            <div class="ls-box-body">
              <span class="ls-board-data">
                <strong>1 <small>milhão</small></strong>
              </span>
            </div>

            <div class="ls-box-footer"></div>
          </div>
        </div>

        <div class="col-sm-6 col-md-4">
          <div class="ls-box">
            <div class="ls-box-head">
              <h6 class="ls-title-4">Próximo HO</h6>
            </div>

            <div class="ls-box-body">
              <span class="ls-board-data">
                <strong>26/10/1987</strong>
              </span>
            </div>

            <div class="ls-box-footer">
              <a href="#" class="ls-btn ls-btn-danger ls-btn-xs">Cancelar</a>
            </div>
          </div>
        </div>

        <div class="col-sm-6 col-md-4">
          <div class="ls-box">
            <div class="ls-box-head">
              <h6 class="ls-title-4">Quantidade de HOs Agendados</h6>
            </div>

            <div class="ls-box-body">
              <span class="ls-board-data">
                <strong>10</strong>
              </span>
            </div>

            <div class="ls-box-footer">
              <a href="#" class="ls-btn ls-btn-xs">Visualizar datas</a>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="ls-box ls-board-box">
      <header class="ls-info-header">
        <h2 class="ls-title-3"><%= t('calendar') %></h2>
      </header>

      <%= month_calendar do |date| %>
        <%= date %>
      <% end %>
    </div>
  </div>

  <%= render 'layouts/footer' %>
</main>

<%= render 'modals/create_ho' %>
<%= render 'modals/destroy_ho' %>

app/views/layouts/_footer.html.erb
<footer class="ls-footer" role="contentinfo">
  <nav class="ls-footer-menu">
    <h2 class="ls-title-footer"><%= t('useful_links') %></h2>
    <ul class="ls-footer-list">
      <li>
        <a href="https://opensource.org/licenses/MIT" target="_blank" class="bg-my-tickets">
          <span class="visible-lg"><%= t('mit_license') %></span>
        </a>
      </li>
      <li>
        <a href="https://github.com/itumoraes/hefesto" target="_blank" class="bg-statusblog">
          <span class="visible-lg"><%= t('github') %></span>
        </a>
      </li>
    </ul>
  </nav>
  <div class="ls-footer-info">
    <div class="ls-footer-info">
      <span class="last-access ls-ico-screen"><strong><%= t('hefesto') %>: </strong><%= t('hefesto_slogan') %></span>
      <p class="ls-copy-right"><%= t('mit_text') %></p>
    </div>
  </div>
</footer>

app/views/layouts/_pre_panel_sidebar.html.erb
<aside class="ls-sidebar">
  <div class="ls-sidebar-inner">
    <h1 class="ls-brand-name ls-ico-earth"><%= link_to t('hefesto'), root_path %></h1>

    <nav class="ls-menu">
      <ul>
        <li><%= link_to t('teams.index.add_team'), new_team_path, remote: true, class: 'ls-ico-plus' %></li>
      </ul>
    </nav>
  </div>
</aside>

app/views/layouts/_pre_panel_topbar.html.erb
<div class="ls-topbar ls-topbar-gray">
  <div class="ls-notification-topbar">

    <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
      <a href="#" class="ls-ico-user">
        <img src="<%= current_user.gravatar_url %>" alt="">
        <span class="ls-name"><%= current_user.name %></span>
        (<%= current_user.username %>)
      </a>

      <nav class="ls-dropdown-nav ls-user-menu">
        <ul>
          <li><%= link_to t('logout'), destroy_user_session_path %></li>
        </ul>
      </nav>
    </div>
  </div>

  <span class="ls-show-sidebar ls-ico-menu"></span>
</div>

app/views/layouts/_sidebar.html.erb
<aside class="ls-sidebar">
  <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
    <a href="#" class="ls-ico-user">
      <img src="/locawebstyle/assets/images/locastyle/avatar-example.jpg" alt="">
      <span class="ls-name"><%= current_user.name %></span>
      (<%= current_user.username %>)
    </a>

    <nav class="ls-dropdown-nav ls-user-menu" aria-hidden="true">
      <ul>
        <li><%= link_to t('logout'), destroy_user_session_path %></li>
      </ul>
    </nav>
  </div>

  <div class="ls-sidebar-inner">
    <nav class="ls-menu" role="navigation">
      <ul role="menu">
        <li><%= link_to t('dashboard'), root_path, class: 'ls-ico-dashboard' %></li>
        <li><%= link_to t('teams.title'), teams_path, class: 'ls-ico-users' %></li>
      </ul>
    </nav>


  </div>
  <span class="ls-sidebar-toggle ls-ico-shaft-left"></span>
</aside>

app/views/layouts/_topbar.html.erb
<div class="ls-topbar ">
  <div class="ls-notification-topbar">
    <div data-ls-module="dropdown" class="ls-dropdown ls-user-account">
      <a href="#" class="ls-ico-user">
        <img src="<%= current_user.gravatar_url %>" alt="">
        <span class="ls-name"><%= current_user.name %></span>
        (<%= current_user.username %>)
      </a>

      <nav class="ls-dropdown-nav ls-user-menu" aria-hidden="true">
        <ul>
          <li><%= link_to t('logout'), destroy_user_session_path %></li>
        </ul>
      </nav>
    </div>
  </div>

  <span class="ls-show-sidebar ls-ico-menu"></span>

  <h1 class="ls-brand-name">
    <a class="ls-ico-earth">
      <% if current_user.team.present? %>
        <small><%= t('hefesto') %></small>
        <%= current_user.team.name %>
      <% else %>
        <small><%= t('hefesto_slogan') %></small>
        <%= t('hefesto') %>
      <% end %>
    </a>
  </h1>

  <span class="ls-show-notifications ls-ico-question"></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="ls-theme-purple ls-html-nobg">
  <head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8">

    <title>Hefesto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag Locastyle.url + '/stylesheets/locastyle.css' %>
    <%= stylesheet_link_tag :application %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag :application %>
    <%= javascript_include_tag Locastyle.url + '/javascripts/locastyle.js' %>
  </body>
</html>

app/views/layouts/pre_panel.html.erb
<!DOCTYPE html>
<html class="ls-theme-purple ls-pre-panel">
  <head>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta charset="utf-8">

    <title>Hefesto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag Locastyle.url + '/stylesheets/locastyle.css' %>
    <%= stylesheet_link_tag :application %>
  </head>

  <body>
    <%= yield %>

    <%= javascript_include_tag :application %>
    <%= javascript_include_tag Locastyle.url + '/javascripts/locastyle.js' %>
  </body>
</html>

app/views/modals/_create_ho.html.erb
<div class="ls-modal" id="ho-modal">
  <%= form_for @home_office do |f| %>
    <div class="ls-modal-box">
      <div class="ls-modal-header">
        <button type="button" data-dismiss="modal">&times;</button>
        <h4 class="ls-modal-title"><%= t('modals.create_ho.title') %></h4>
      </div>
      <div class="ls-modal-body">
        <p><%= raw t('modals.create_ho.text') %></p>
      </div>
      <div class="ls-modal-footer">
        <button type="button" class="ls-btn ls-float-right" data-dismiss="modal"><%= t('cancel') %></button>
        <button type="submit" class="ls-btn-primary"><%= t('confirm') %></button>
      </div>
    </div>
    <%= f.hidden_field :date %>
  <% end %>
</div>

app/views/modals/_destroy_ho.html.erb
<div class="ls-modal" id="destroy-ho-modal">
  <%= form_tag '', method: :delete do |f| %>
    <div class="ls-modal-box">
      <div class="ls-modal-header">
        <button type="button" data-dismiss="modal">&times;</button>
        <h4 class="ls-modal-title"><%= t('modals.destroy_ho.title') %></h4>
      </div>
      <div class="ls-modal-body">
        <p><%= raw t('modals.destroy_ho.text') %></p>
      </div>
      <div class="ls-modal-footer">
        <button type="button" class="ls-btn ls-float-right" data-dismiss="modal"><%= t('cancel') %></button>
        <button type="submit" class="ls-btn-primary"><%= t('confirm') %></button>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="<%= locastyle_class_for_alert(key) %> ls-dismissable">
    <span data-ls-module="dismiss" class="ls-dismiss">&times;</span>
    <%= value %>
  </div>
<% end %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to '', calendar.url_for_previous_view, class: 'ls-ico-chevron-left ls-btn ls-btn-xs', alt: t('simple_calendar.previous'), title: t('simple_calendar.previous') %>
    <span class="calendar-title ls-color-theme"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to '', calendar.url_for_next_view, class: 'ls-ico-chevron-right ls-ico-right ls-btn ls-btn-xs', alt: t('simple_calendar.next'), title: t('simple_calendar.next') %>
  </div>

  <table class="table table-striped calendar-table">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |date| %>
            <%= content_tag :td, data: { td_date: date.to_s }, class: calendar.td_classes_for(date) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(date, sorted_events.fetch(date, []), &block) %>
              <% else %>
                <% @home_offices.each do |ho| %>
                  <% if ho.date == date %>
                    <%= content_tag :span, title: ho.user.name, class: home_office_css(ho) do %>
                      <%= image_tag(ho.user.gravatar_url, alt: ho.user.name) %>
                      <%= link_to '', '', class: 'calendar-action calendar-del-ho ls-ico-minus',
                                          'aria-label': ho.user.name,
                                          data: { date: date.to_s, action: home_office_path(ho), ls_module: 'modal', target: '#destroy-ho-modal' } if current_user_home_office?(ho) %>
                    <% end %>
                  <% end %>
                <% end %>
                <%= link_to '', '', class: 'calendar-add-ho calendar-action ls-ico-plus', data: { date: date.to_s, ls_module: 'modal', target: '#create-ho-modal' } unless home_office_at_date?(date) %>
                <time class="calendar-day"><%= date.day %></time>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= start_date.strftime("%U").to_i %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>